export { default as HelloWorld } from "@/components/HelloWorld.vue"
export { default as CreateAdministrator } from "@/components/CreateAdministrator.vue"
export { default as GenericTable } from "@/components/GenericTable.vue"
export { default as BaseModalDialog } from "@/components/BaseModalDialog.vue"
export { default as EditAdministratorModalDialog } from "@/components/Administration/EditAdministratorModalDialog.vue"
