export { default as Home } from "@/views/Home.vue"
export { default as About } from "@/views/About.vue"
export { default as Administration } from "@/views/Administration.vue"
export { default as GenericView } from "@/views/GenericView.vue"
export { default as GenericView2 } from "@/views/GenericView2.vue"